version: '3'

services:
  hosting:
    build: .
    privileged: true
    ports:
      - "80:80"
      - "8888:8888"
      - "8808:8808"
      - "0.0.0.0:21:21"
      - "0.0.0.0:20:20"
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./src:/opt
      - ./.docker/.www:/var/www
      - ./.docker/postgres/data:/var/lib/postgresql/15/data
      - ./.docker/dnsmasq/addn.hosts:/etc/dnsmasq.d/addn.hosts
      - ./.docker/nginx/http.d:/etc/nginx/http.d
      - ./.docker/vsftpd/virtual_users:/etc/vsftpd/virtual_users
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: master