version: '3'

services:
  hosting:
    build: .
    volumes:
      - ./.docker/.www:/var/www
      - ./.docker/postgres/data:/var/lib/postgresql/15/data
      - ./.docker/dnsmasq/users.hosts.dat:/etc/dnsmasq.d/users.hosts.dat
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/http.d:/etc/nginx/http.d
      - ./.docker/vsftpd/virtual_users:/etc/vsftpd/virtual_users
